---
Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &Producer
        Name: ProducerMSP
        ID: ProducerMSP
        MSPDir: crypto-config/peerOrganizations/producer.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ProducerMSP.admin', 'ProducerMSP.peer', 'ProducerMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ProducerMSP.admin', 'ProducerMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ProducerMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('ProducerMSP.peer')"
            
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.producer.example.com
              Port: 7051

    - &Manufacturer
        Name: ManufacturerMSP
        ID: ManufacturerMSP
        MSPDir: crypto-config/peerOrganizations/manufacturer.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ManufacturerMSP.admin', 'ManufacturerMSP.peer', 'ManufacturerMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ManufacturerMSP.admin', 'ManufacturerMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ManufacturerMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('ManufacturerMSP.peer')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.manufacturer.example.com
              Port: 9051
                
    - &Deliverer
        Name: DelivererMSP
        ID: DelivererMSP
        MSPDir: crypto-config/peerOrganizations/deliverer.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('DelivererMSP.admin', 'DelivererMSP.peer', 'DelivererMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('DelivererMSP.admin', 'DelivererMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('DelivererMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('DelivererMSP.peer')"
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.deliverer.example.com
              Port: 10051

                
    - &Retailer
        Name: RetailerMSP
        ID: RetailerMSP
        MSPDir: crypto-config/peerOrganizations/retailer.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('RetailerMSP.admin', 'RetailerMSP.peer', 'RetailerMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('RetailerMSP.admin', 'RetailerMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('RetailerMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('RetailerMSP.peer')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.retailer.example.com
              Port: 8051

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
          Type: ImplicitMeta
          Rule: "MAJORITY Endorsement"
        Endorsement:
          Type: ImplicitMeta
          Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft

    EtcdRaft:
        Consenters:
        - Host: orderer.example.com
          Port: 7050
          ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt


    Addresses:
        - orderer.example.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    SupplyOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Producer
                    - *Manufacturer
                    - *Deliverer
                    - *Retailer
    SupplyChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Producer
                - *Manufacturer
                - *Deliverer
                - *Retailer
            Capabilities:
                <<: *ApplicationCapabilities