OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
            - "localhost"
            - "127.0.0.1"

PeerOrgs:
  - Name: Producer
    Domain: producer.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - "localhost"
    Users:
      Count: 1

  - Name: Manufacturer
    Domain: manufacturer.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - "localhost"
    Users:
      Count: 1

  - Name: Deliverer
    Domain: deliverer.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - "localhost"
    Users:
      Count: 1
      
  - Name: Retailer
    Domain: retailer.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - "localhost"
    Users:
      Count: 1